### ISSUE TITLE
Changing presets causes crash

### ISSUE THREAD

**Issue by Fietspomp86** [notspiff/visualization.projectm#44]
So, love the ProjectM addon but unfortunately it's crashing when it changes a preset.
I though it was due to the one-thread bug but that seems to be solved.

Running on the latest LibreElec (9.2.0) and latest ProjectM (2.3.4.1).
I'll try to search the debug log for some usefull information.
There was a thread on the Kodi forum so at least I'm not the only one :-)

**Comment by AlwinEsch** [comment]
Does it crash (LibreElec direct restart Kodi) or frezze it (and need power reset), maybe related to https://github.com/xbmc/visualization.projectm/issues/45 ?

**Comment by Fietspomp86** [comment]
> Does it crash (LibreElec direct restart Kodi) or frezze it (and need power reset), maybe related to #45 ?

It's exactly the same as #45 , don't know why 2 issues are opened now.
But it doesn't need a reboot, going into SSH and typing "systemctl restart kodi" also works.
Anyway, I checked my logs and there's nothing about ProjectM there.

My hardware is a 64 bit normal PC, with dualboot Windows and Libreelec.

**Comment by Fietspomp86** [comment]
Just updated to version 2.3.5.1 from the Libreelec repository, still the same issue unfortunately!

**Comment by w1ll14m** [comment]
> Just updated to version 2.3.5.1 from the Libreelec repository, still the same issue unfortunately!

It looks like it's fixed in 2.3.5.3 but this version of the addon is not in the official LibreElec repo yet.

**Comment by Fietspomp86** [comment]
Great, I'll try to compile it myself tonight and see if it works.

**Comment by w1ll14m** [comment]
> Great, I'll try to compile it myself tonight and see if it works.

This should do the trick and the complete addon will be in target/addons:
git checkout libreelec-9.2
PROJECT=Generic ARCH=x86_64 scripts/create_addon visualization.projectm

Veel plerzier!

**Comment by Fietspomp86** [comment]
> > Great, I'll try to compile it myself tonight and see if it works.
> 
> This should do the trick and the complete addon will be in target/addons:
> git checkout libreelec-9.2
> PROJECT=Generic ARCH=x86_64 scripts/create_addon visualization.projectm
> 
> Veel plerzier!

Yes, been running my compiled version for an hour and it works!
I've attached it here for people to try as well.
When I get more positive reactions I'll close the issue.
Mine is compiled for x86_64
[visualization.projectm-2.3.5.3.zip](https://github.com/xbmc/visualization.projectm/files/4465151/visualization.projectm-2.3.5.3.zip)

EDIT: It's also in the Libreelec repo now :-)

**Comment by jamesgrace** [comment]
LibreELEC 9.2.2 : just upgraded to projectM version 2.3.5.3 which seems to be running smoothly !

**Comment by wimb0** [comment]
FYI: The problem still exists in the Kodi Matrix projectM plugin, version 3.0.1.1.

**Comment by w1ll14m** [comment]
> FYI: The problem still exists in the Kodi Matrix projectM plugin, version 3.0.1.1.

I think for matrix it's fixed in version 3.0.1.2. The issue was fixed by changes to libprojectm version 3.1.2

See https://github.com/LibreELEC/LibreELEC.tv/commit/a88074841043605d36b9b48401789acf57c477be#diff-cdc62e3cbd0e412f9ebeaea886a4590a

you can try this version that i compiled recently for LibreELEC but of course no guarantees :)
[visualization.projectm-3.0.1.3.zip](https://github.com/xbmc/visualization.projectm/files/4491981/visualization.projectm-3.0.1.3.zip)

**Comment by AlwinEsch** [comment]
Yes, by libreelec we must aware, there is the libreelec not created by addon and created byself and installed in system. Even I sometimes forget that.

Good to hear that with ProjectM lib version 3.1.2 it is fixed.

**Comment by osirase** [comment]
Hmmm interesting, I'm getting crashes on 'some' preset changes. I don't know how to get useful information out of kodi but I've tried to have a look. I'll compile the latest version again and test it in kodi then report back here in a couple of days

**Comment by osirase** [comment]
Alright so I'm still getting crashes, it's hard to say if it's on preset transition or not though. I compiled 2.3.5 from source on Fedora 32 running a AMD Ryzen 3400G. If anyone knows how to run this in a way that gets useful debug output on the crash that'd be great.

**Comment by kblaschke** [comment]
We've fixed numerous crash issues in projectM, with the last remaining (obvious) bugs recently merged (See https://github.com/projectM-visualizer/projectm/issues/407).

The upcoming 4.0 release will hopefully run more stable.
